MAINT: 1 replace on_trait_change 2 remove import *
enthought/scimath pull request #164
Opened 2023-03-07 08:55 UTC by homosapien-lcy

Fixing issue #143 #145

2023-03-07 09:09 UTC, mdickinson requested changes
Needs fixes for test failures.

2023-03-07 09:29 UTC, homosapien-lcy commented
> 

Hi Mark: thx, I previous thought I just need to do the replacing for these two issues so I didn't setup a local env. Could you send my information on env setup?

2023-03-07 09:35 UTC, mdickinson commented
> Could you send my information on env setup?

Hmm. Ideally, the README in this repository would give that information, but it seems it needs updating. Please could you open a separate issue for updating the README to include information about development environment setup.

Without README instructions, the best resource for this kind of thing is often the CI workflows. If you look at the file https://github.com/enthought/scimath/blob/main/.github/workflows/test-with-edm.yml, you'll see the steps needed to create a development environment and run the test suite in it.

Briefly:

- Create an EDM bootstrap environment containing at least `click`, `setuptools` and `coverage`
- In that bootstrap environment, run `python etstool.py install` to create an EDM development environment.
- Again in that bootstrap environment, run `python etstool.py test` to run the tests.

Let me know if you get stuck on any of the steps above.

In general for anything but really tiny changes (e.g., fixing a typo in a comment), I'd strongly recommend always working with an actual development environment, where you can test your changes manually to check that they work before submitting a PR.

2023-03-07 09:42 UTC, homosapien-lcy commented
> > Could you send my information on env setup?
> 
> Hmm. Ideally, the README in this repository would give that information, but it seems it needs updating. Please could you open a separate issue for updating the README to include information about development environment setup?
> 
> Without README instructions, the best resource for this kind of thing is often the CI workflows. If you look at the file https://github.com/enthought/scimath/blob/main/.github/workflows/test-with-edm.yml, you'll see the steps needed to create a development environment and run the test suite in it.
> 
> Briefly:
> 
> * Create an EDM bootstrap environment containing at least `click`, `setuptools` and `coverage`
> * In that bootstrap environment, run `python etstool.py install` to create an EDM development environment.
> * Again in that bootstrap environment, run `python etstool.py test` to run the tests.
> 
> Let me know if you get stuck on any of the steps above.
> 
> In general for anything but really tiny changes (e.g., fixing a typo in a comment), I'd strongly recommend always working with an actual development environment, where you can test your changes manually to check that they work before submitting a PR.

Got it thanks! The issue for readme update is opened: https://app.zenhub.com/workspaces/ets-queue-priority-64022b3641e35b00166c1272/issues/gh/enthought/scimath/165

2023-03-08 11:52 UTC, mdickinson commented
> The issue for readme update is opened: https://app.zenhub.com/workspaces/ets-queue-priority-64022b3641e35b00166c1272/issues/gh/enthought/scimath/165

Thanks! Let's use direct GitHub references for issues (otherwise people who don't have access to ZenHub won't be able to follow the link). So any of the following would work:

* https://github.com/enthought/scimath/pull/164 (`https://github.com/enthought/scimath/pull/164`)
* enthought/scimath#164 (`enthought/scimath#164`)
* #164 (`#164`)

2023-03-08 12:13 UTC, mdickinson requested changes
Thanks for the updates; we're getting there, but there are a couple more things to fix.

2023-03-08 12:13 UTC, mdickinson commented on README.rst
> +Development Environment Setup
Thank you for these changes!

In the interests of avoiding feature creep, and getting PRs merged effectively, please could you move these changes to a separate PR? Then we can keep this one focused on the issues it was originally trying to solve.

I have a few comments on the README updates, but I'll save them for the new PR.

2023-03-08 12:13 UTC, mdickinson commented on scimath/units/geo_units.py
> +from scimath.units.SI import ampere, atto, becquerel, candela, centi, \
Let's import `unit`, `dimensionless` and `none` from `scimath.units.unit` (the module where they're defined) instead of from `scimath.units.SI`.

2023-03-09 00:10 UTC, homosapien-lcy commented
I think both this issue (#165) and the two other issues related (import issue #143 and observe issue #145)

2023-03-09 08:26 UTC, mdickinson approved these changes
LGTM

2023-03-09 08:28 UTC, merged